apiVersion: v1
kind: ConfigMap
metadata:
  name: techpathway-config
  namespace: techpathway-ns
data:
  AWS_REGION: us-east-1
  NOTIFICATION_SERVICE_URL: http://action-messages-service:5001
  WAREHOUSE_SERVICE_URL: http://techpathway-warehouse-service:5002
