apiVersion: apps/v1
kind: Deployment
metadata:
  name: techpathway-warehouse
  namespace: techpathway-ns

spec:
  replicas: 1

  selector:
    matchLabels:
      app: techpathway-warehouse

  template:
    metadata:
      labels:
        app: techpathway-warehouse

    spec:
      containers:
        - name: techpathway-warehouse
          image: 856705507609.dkr.ecr.us-east-1.amazonaws.com/techpathway-warehouserepo:v1

          ports:
            - containerPort: 5002

          envFrom:
            - configMapRef:
                name: techpathway-config
            - secretRef:
                name: techpathway-secret

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"

          readinessProbe:
            httpGet:
              path: /health
              port: 5002
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 5002
            initialDelaySeconds: 15
            periodSeconds: 20
