apiVersion: v1
kind: Service
metadata:
  name: weekly-call-service
  namespace: techpathway-ns
spec:
  selector:
    app: weekly-call
  ports:
    - port: 5111
      targetPort: 5111
  type: ClusterIP
