apiVersion: apps/v1
kind: Deployment
metadata:
  name: weekly-call
  namespace: techpathway-ns

spec:
  replicas: 1

  selector:
    matchLabels:
      app: weekly-call

  template:
    metadata:
      labels:
        app: weekly-call

    spec:
      containers:
        - name: weekly-call
          image: 856705507609.dkr.ecr.us-east-1.amazonaws.com/weekly-callrepo:v1

          ports:
            - containerPort: 5111

          envFrom:
            - configMapRef:
                name: techpathway-config
            - secretRef:
                name: techpathway-secret

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"

          readinessProbe:
            httpGet:
              path: /health
              port: 5111
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 5111
            initialDelaySeconds: 15
            periodSeconds: 20
